import { Page } from '../types';

export const storyData: Page[] = [
  {
    id: 0,
    title: "L'Aventura Màgica de la Ivet",
    text: "Una història interactiva on les teves decisions canvien el destí del bosc màgic.\n\nFes clic per començar l'aventura!",
    image: '/images/illustration-cover.jpg',
    choices: [
      { text: 'Començar Aventura', goToPage: 1 },
    ],
  },
  {
    id: 1,
    title: 'DESCOBRIMENT DEL PROBLEMA',
    text: "La Ivet camina pel seu bosc màgic preferit amb la seva vareta a la mà. Avui alguna cosa va malament. Les flors que sempre brillaven amb colors intensos ara semblen apagades i grises. Intenta fer un encanteri senzill per illuminar un camí, però la seva vareta només fa unes guspires febles. \"Que estrany!\", pensa preocupada. Una esquirol s'acosta corrents. \"Bruixa Ivet, la màgia del bosc està desapareixent! Les criatures estem perdent les nostres habilitats especials.\" La Ivet mira al seu voltant i s'adona que té raó. Ha de descobrir què està passant abans que sigui massa tard.",
    image: '/images/illustration-1.jpg',
    choices: [
      { text: 'Seguir el rastre de màgia perduda', goToPage: 2 },
      { text: "Buscar ajuda de la Gran Òliba sàvia", goToPage: 3 },
    ],
  },
  {
    id: 2,
    title: 'RASTRE MÀGIC',
    text: "La Ivet tanca els ulls i fa girar la vareta. \"Revela't, camí de llum antiga\", xiuxiueja. Un rastre brillant i daurat apareix al terra, però es va apagant a mesura que avança. Camina ràpidament seguint les marques lluminoses que la porten cada cop més endins del bosc. Després de mitja hora, arriba a una cruïlla. A l'esquerra, sent el soroll de l'aigua del riu màgic que sempre ha estat ple de vida. A la dreta, veu l'entrada d'una cova antiga coberta de molsa que mai havia explorat. El rastre es divideix en dues direccions diferents. Ha de triar bé.",
    image: '/images/illustration-2.jpg',
    choices: [
      { text: 'Anar cap al riu màgic', goToPage: 4 },
      { text: 'Anar cap a la cova antiga', goToPage: 5 },
    ],
  },
  {
    id: 3,
    title: "L'ÒLIBA SÀVIA",
    text: "La Ivet corre cap al Roure més alt del bosc, on viu la Gran Òliba. \"Òliba sàvia, necessito la teva ajuda!\" L'ocell obre els seus grans ulls daurats. \"Ja sé per què vens, petita bruixa. La màgia del bosc s'està apagant.\" L'òliba li explica una antiga profecia: \"La màgia torna al lloc on va néixer\". Li dóna dues pistes importants. \"Busca al Roure Ancestral, el primer arbre del bosc, o vés al Llac de Cristall, on la màgia es va reflectir per primera vegada.\" La Ivet escolta amb atenció. Sap que aquestes pistes són valuoses, però només pot triar una.",
    image: '/images/illustration-3.jpg',
    choices: [
      { text: 'Anar al Roure Ancestral', goToPage: 6 },
      { text: 'Anar al Llac de Cristall', goToPage: 7 },
    ],
  },
  {
    id: 4,
    title: 'EL RIU MÀGIC',
    text: "La Ivet arriba al riu i es queda sorpresa. L'aigua, que abans brillava amb tons blaus i platejats, ara sembla opaca. Veu algú al marge. És l'Emma! La seva germana gran està asseguda amb una canya de pescar. \"Ivet! Què fas aquí?\" L'Emma li explica que ha vingut a pescar però tots els peixos màgics han desaparegut. De sobte, totes dues veuen una llum estranya sota l'aigua, al fons del riu. Brilla amb una tonalitat fosca i violeta que no sembla natural. L'Emma mira la Ivet. \"Creus que això té a veure amb el problema?\"",
    image: '/images/illustration-4.jpg',
    choices: [
        { text: "Nedar fins a la llum", goToPage: 8 },
        { text: "Fer un encanteri per veure què hi ha sota", goToPage: 9 },
    ],
  },
  {
    id: 5,
    title: 'LA COVA ANTIGA',
    text: "La Ivet entra a la cova fosca. Illumina el camí amb la sua vareta, però la llum és feble. \"Llum persistent, guia'm endins\", diu concentrada. Aleshores escolta un crit. \"Ajuda!\" És la veu de la Judit! Corre cap endins i troba la sua germana petita atrapada en una teranyina màgica brillant. \"Judit! Com has arribat aquí?\" La Ivet fa servir la vareta per tallar els fils amb cuidado. Quan la Judit és lliure, assenyala les parets de la cova. Hi ha símbols estranys gravats que brillen lleugerament. Semblen molt antics i misteriosos.",
    image: '/images/illustration-5.jpg',
    choices: [
      { text: "Intentar desxifrar els símbols", goToPage: 10 },
      { text: "Seguir endins de la cova", goToPage: 11 },
    ],
  },
  {
    id: 6,
    title: 'EL ROURE ANCESTRAL',
    text: "La Ivet camina fins al centre més antic del bosc. Allà troba el Roure Ancestral, un arbre immens i vell de segles. Però alguna cosa va malament. El Roure està perdent fulles i les seves branques semblen febles. Al peu de l'arbre, veu l'Emma i la Judit recollint baies màgiques del terra. \"Germanes! Què feu aquí?\" L'Emma li ensenya les baies. \"Abans brillaven, Ivet, però ara estan apagades.\" La Judit toca el tronc del Roure. \"Sembla malalt.\" En aquell moment, el Roure parla amb veu cansada: \"La font de la meva força s'està perdent...\"",
    image: '/images/illustration-6.jpg',
    choices: [
      { text: "Usar encanteri curatiu al Roure", goToPage: 12 },
      { text: "Buscar l'arrel del problema sota terra", goToPage: 13 },
    ],
  },
  {
    id: 7,
    title: 'EL LLAC DE CRISTALL',
    text: "La Ivet arriba al Llac de Cristall però es queda sense paraules. El llac, que sempre havia estat tan transparent que podien veure fins al fons, ara està ennuvolat i gris. A la vora troba la Judit llançant pedres a l'aigua. \"Judit! Què fas aquí sola?\" La seva germaneta es gira. \"Volia veure els peixos de colors però l'aigua està bruta.\" De sobte, totes dues veuen una ombra enorme moure's al fons del llac. És massa gran per ser un peix. La Ivet agafa la vareta, preparada per qualsevol cosa.",
    image: '/images/illustration-7.jpg',
    choices: [
        { text: "Convocar la criatura del llac", goToPage: 14 },
        { text: "Buscar què està contaminant l'aigua", goToPage: 15 },
    ],
  },
   {
    id: 8,
    title: "SOTA L'AIGUA",
    text: "La Ivet i l'Emma es treuen les sabates. \"Encanteri de respiració aquàtica!\" diu la Ivet assenyalant amb la vareta. Una bombolla d'aire envolta els seus caps. Neden cap a la llum fosca del fons. Allà troben una pedra negra de forma estranya que absorbeix tota la màgia del voltant. L'Emma, valenta, la toca i nota com li xucla l'energia. \"És horrible!\" La Ivet sap que aquesta pedra és el problema, però és perillosa. Les dues germanes s'agafen de la mà, preparades per actuar. Han de decidir ràpidament perquè l'aire de la bombolla no durarà gaire.",
    image: '/images/illustration-8.jpg',
    choices: [
      { text: "Trencar la pedra amb màgia", goToPage: 16 },
      { text: "Treure la pedra de l'aigua", goToPage: 17 },
    ],
  },
  {
    id: 9,
    title: 'ENCANTERI DE VISIÓ',
    text: "La Ivet apunta la vareta cap a l'aigua. \"Aigües clares, reveleu el secret!\" Un cercle de llum es forma a la superfície i poden veure perfectament el fons. El que descobreixen les deixa bocabadades. Hi ha un portal màgic obert, un cercle brillant que gira i gira absorbint la màgia del bosc. El portal sembla que s'està tancant lentament. L'Emma agafa el braç de la Ivet. \"S'està tancant! Si volem fer alguna cosa, ha de ser ara!\" La Ivet pensa ràpidament. Podrien entrar al portal o intentar tancar-lo del tot.",
    image: '/images/illustration-9.jpg',
    choices: [
      { text: "Entrar al portal", goToPage: 18 },
      { text: "Tancar el portal amb màgia", goToPage: 19 },
    ],
  },
  {
    id: 10,
    title: 'SÍMBOLS DE LA COVA',
    text: "La Ivet i la Judit s'acosten a la paret de la cova. Els símbols brillen amb llum verda. La Ivet toca un amb la vareta i les lletres es reorganitzen formant paraules que poden llegir. El missatge diu: \"El guardià del bosc va ser traït i empresonat. Sense ell, la màgia mor.\" La Judit busca pel voltant i troba una clau de plata amagada en una esquerda. \"Ivet, mira!\" La clau té gravada una imatge d'una fada. La Ivet entén que aquesta clau és important. Podrien buscar el guardià empresonat o explorar si hi ha una porta secreta.",
    image: '/images/illustration-10.jpg',
    choices: [
      { text: "Buscar el guardià", goToPage: 16 },
      { text: "Usar la clau a la porta secreta", goToPage: 20 },
    ],
  },
  {
    id: 11,
    title: 'ENDINS DE LA COVA',
    text: "La Ivet i la Judit s'endinsen més a la cova. El camí baixa i baixa fins arribar a una sala enorme. Al centre hi ha un drac petit, no més gran que un gos, fermat amb cadenes màgiques brillants. El drac les mira amb ulls tristos. Sembla molt feble i malalt. \"Ajudeu-me\", diu amb veu cansada. La Judit vol córer a alliberar-lo immediatament. \"És tan petit i sembla tan trist!\" Però la Ivet dubta. Potser el van empresonar per alguna raó important. Ha de decidir si confiar en el drac o investigar abans.",
    image: '/images/illustration-11.jpg',
    choices: [
      { text: "Alliberar el drac", goToPage: 21 },
      { text: "Primer investigar per què està empresonat", goToPage: 22 },
    ],
  },
  {
    id: 12,
    title: 'CURAR EL ROURE',
    text: "La Ivet col·loca les mans al tronc del Roure Ancestral. \"Energia vital, flueix i cura!\" Una llum verda surt de la seva vareta i envolta l'arbre. El Roure recupera una mica de color i algunes fulles noves comencen a créixer. L'Emma i la Judit aplaudeixen contents. Però el Roure parla: \"Gràcies, petita bruixa, però la meva curació no és completa. La veritable font de màgia està trencada en un altre lloc del bosc.\" Les branques de l'arbre assenyalen dues direccions: el nord fosc i el sud assolellat. La Ivet ha de triar.",
    image: '/images/illustration-12.jpg',
    choices: [
      { text: "Buscar la font al nord", goToPage: 16 },
      { text: "Buscar la font al sud", goToPage: 23 },
    ],
  },
  {
    id: 13,
    title: 'SOTA EL ROURE',
    text: "La Ivet, l'Emma i la Judit comencen a excavar al voltant de les arrels del Roure. Amb l'ajuda d'un encanteri d'excavació, troben alguna cosa estranya. Unes arrels negres i podrides que s'estenen pel subsol, absorbint tota la màgia que toquen. Són com paràsits. \"Això està matant el Roure i tot el bosc!\" exclama l'Emma. La Judit les toca i retira la mà de seguida. \"Fan mal!\" La Ivet pensa en què fer. Podria cremar les arrels amb foc màgic o intentar purificar-les amb un encanteri de neteja. Cada opció té riscos.",
    image: '/images/illustration-13.jpg',
    choices: [
      { text: "Cremar les arrels", goToPage: 24 },
      { text: "Purificar amb màgia", goToPage: 25 },
    ],
  },
  {
    id: 14,
    title: 'CRIATURA DEL LLAC',
    text: "La Ivet alça la vareta cap al cel. \"Guardiana de les aigües, et convoco!\" El llac comença a moure's i de l'aigua surt una sirena preciosa amb cua platejada. \"Qui m'ha cridat?\" La Ivet explica el problema de la màgia desapareguda. La sirena sospira tristament. \"Algú ha robat la Perla de Llum del llac. Sense ella, les aigües perden la màgia i es contaminen.\" La Judit, que ha estat escoltant, s'acosta. \"Podem ajudar-te a trobar-la!\" La sirena somriu. Poden buscar el lladre o intentar crear una nova perla amb màgia.",
    image: '/images/illustration-14.jpg',
    choices: [
      { text: "Buscar el lladre", goToPage: 16 },
      { text: "Crear una nova perla amb màgia", goToPage: 26 },
    ],
  },
  {
    id: 15,
    title: 'CONTAMINACIÓ',
    text: "La Ivet i la Judit caminen per la vora del llac buscant pistes. Troben un camí de líquid fosc que va cap al fons. La Ivet fa un encanteri per baixar l'aigua del llac temporalment. Al fons descobreixen dotzenes d'ampolles trencades amb restes de pocions fosques i màliques. \"Algú ha abocat això aquí a propòsit!\" diu la Judit enfadada. Les dues germanes comencen a recollir les ampolles amb cuidado. Són perilloses i contaminen l'aigua. La Ivet sap que podria neutralitzar les pocions o seguir el rastre de qui les va deixar aquí.",
    image: '/images/illustration-15.jpg',
    choices: [
      { text: "Neutralitzar les pocions", goToPage: 27 },
      { text: "Seguir el rastre de qui les va deixar", goToPage: 28 },
    ],
  },
  {
    id: 16,
    title: 'EL GUARDIÀ OBLIDAT',
    text: "La Ivet arriba a una part amagada del bosc que mai havia vist. Enmig d'un cercle de pedres antigues, troba una petita fada ancià atrapada dins d'una gàbia de llum. Les ales de la fada quasi no brillen. \"Per fi algú em troba!\" diu amb veu feble. \"Sóc la Guardiana del Bosc. Fa anys que em van empresonar aquí i des d'aleshores la màgia s'ha anat morint.\" Les germanes l'envolten preocupades. La Ivet veu que pot trencar la gàbia amb un encanteri fort. Però potser seria millor escoltar primer la història completa.",
    image: '/images/illustration-16.jpg',
    choices: [
      { text: "Alliberar-la immediatament", goToPage: 29 },
      { text: "Preguntar-li què va passar abans", goToPage: 30 },
    ],
  },
  {
    id: 17,
    title: "FINAL MITJÀ (OBERT)",
    text: "La Ivet i l'Emma agafen la pedra negra i amb molt d'esforç la treuen de l'aigua. Quan toca l'aire, la pedra es trenca en mil bocins que desapareixen. Immediatament, una part de la màgia torna al bosc. Les flors recuperen una mica de color i els animals semblen més feliços. Però la Ivet nota que no s'ha restaurat del tot. \"Hem solucionat part del problema, però no tot\", diu pensativa. L'Emma i la Judit l'abracen. \"Almenys el bosc està millor!\" Les tres germanes prometen tornar per descobrir què més falta arreglar. L'aventura no ha acabat.",
    image: '/images/illustration-17.jpg',
    choices: [],
    ending: "FI - Has descobert un final!",
  },
  {
    id: 18,
    title: 'FINAL BO',
    text: "La Ivet i l'Emma salten dins del portal just abans que es tanqui. Cauen en una cambra secreta plena de cristalls brillants. Al centre hi ha el Nucli de Màgia del Bosc, una esfera gegant de llum pura que està trencada. \"Això és el que alimenta tot el bosc!\" exclama l'Emma. La Ivet assenyala amb la vareta i diu un encanteri de reparació creatiu: \"Trencadís a plenitud, retorna la virtut!\" El Nucli es cura i explota en mil colors. Quan tornen al bosc, tot ha tornat a la normalitat. Les criatures celebren i les tres germanes són les heroïnes del dia.",
    image: '/images/illustration-18.jpg',
    choices: [],
    ending: "FI - Has aconseguit el millor final!",
  },
  {
    id: 19,
    title: 'FINAL DOLENT',
    text: "La Ivet apunta la vareta cap al portal. \"Encanteri de clausura total!\" El portal es tanca completament amb un soroll fort. L'Emma i la Ivet surten de l'aigua contents. Però al cap de pocs minuts, es donen compte que el bosc es torna encara més gris. El portal era la connexió amb la font de màgia i l'han tancat per sempre. \"Què hem fet?\" diu la Ivet horroritzada. Les criatures del bosc estan encara més febles. Han empitjorat el problema i ara no saben com arreglar-ho. Hauran de buscar una altra solució, però serà molt difícil.",
    image: '/images/illustration-19.jpg',
    choices: [],
    ending: "FI - No ha sortit bé aquesta vegada",
  },
  {
    id: 20,
    title: 'FINAL OBERT',
    text: "La Ivet i la Judit descobreixen una porta secreta a la paret de la cova. La clau de plata encaixa perfectament. Quan obren la porta, veuen un món parallel increïble ple de màgia pura, colors impossibles i criatures fantàstiques. \"Uau!\" exclamen totes dues. Una veu màgica els diu: \"Podeu quedar-vos aquí per sempre o tornar al vostre bosc.\" La Ivet mira la Judit. El bosc encara necessita ajuda, però aquest món nou és fascinant. Hauran de pensar bé què fer. La decisió canviarà les seves vides per sempre.",
    image: '/images/illustration-20.jpg',
    choices: [],
    ending: "FI - Una nova aventura comença!",
  },
  {
    id: 21,
    title: 'FINAL BO',
    text: "La Ivet decideix confiar en el drac. \"Trenca't, empresonament cruel!\" Les cadenes es fan miques. El drac petit comença a créixer fins a convertir-se en un drac magnífic i preciós. \"Gràcies! Sóc el Guardià Drac del Bosc. Em van empresonar bruixes dolentes fa molt de temps.\" El drac alça el vol i expulsa una flama daurada que retorna tota la màgia al bosc. Com a regal, dóna a les tres germanes la capacitat de parlar amb tots els animals. \"Ara sereu sempre benvingudes al meu bosc\", diu el drac. Les nenes han salvat el dia!",
    image: '/images/illustration-21.jpg',
    choices: [],
    ending: "FI - Victòria màgica!",
  },
  {
    id: 22,
    title: 'FINAL DOLENT',
    text: "La Ivet decideix investigar abans d'actuar. Busca informació sobre per què el drac està empresonat. Llegeix llibres antics, pregunta a criatures i passa massa temps investigant. Quan finalment torna a la cova, el drac ja està mort. Les cadenes el van debilitar massa. La màgia del bosc es perd per sempre perquè el drac era el veritable guardià. La Ivet plora amargament. \"Hauria d'haver confiat i actuat ràpid.\" Aquesta lliçó l'acompanyarà sempre: de vegades cal confiar en el cor i no pensar-s'ho massa.",
    image: '/images/illustration-22.jpg',
    choices: [],
    ending: "FI - Una lliçó dura",
  },
  {
    id: 23,
    title: 'FINAL OBERT',
    text: "La Ivet, l'Emma i la Judit caminen cap al sud del bosc. Després d'una llarga caminada, troben una font de màgia diferent: un pou antic ple d'aigua brillant color ametista. No és tan potent com la màgia original, però és suficient per mantenir el bosc viu. Quan connecten aquesta nova font al Roure Ancestral, el bosc canvia. Les flors tenen colors nous, les criatures desenvolupen habilitats diferents. El bosc s'ha transformat en alguna cosa nova i misteriosa que hauran d'explorar i entendre.",
    image: '/images/illustration-23.jpg',
    choices: [],
    ending: "FI - Un nou començament!",
  },
  {
    id: 24,
    title: 'FINAL DOLENT',
    text: "La Ivet crea flames màgiques a les mans. \"Foc purificador!\" Crema totes les arrels negres. Al principi sembla que funciona, però aleshores el Roure comença a tremolar. Les arrels negres eren part del sistema màgic original del bosc, només estaven podrides. En cremar-les, han trencat l'equilibri natural. El Roure cau malalt de debò i el bosc comença a morir més ràpid. \"No, no, no!\" crida la Ivet desesperada. Han comès un error greu. Ara hauran de viure amb les conseqüències de no pensar abans d'actuar.",
    image: '/images/illustration-24.jpg',
    choices: [],
    ending: "FI - Algunes decisions no es poden desfer",
  },
  {
    id: 25,
    title: 'FINAL BO',
    text: "La Ivet col·loca les mans sobre les arrels negres. \"Màgia neta, ànima pura, que la salut perduri!\" Una llum blanca envolta les arrels que poc a poc recuperen el color marró natural. El verí desapareix completament. L'Emma i la Judit ajuden canalitzant la seva energia positiva. El Roure recupera força i les seves fulles tornen a brillar. \"Algú havia enverinat les arrels a propòsit\", explica el Roure agraït. Com a regal, l'arbre els dóna un amulet protector de fusta que sempre les protegirà. El bosc està salvat gràcies a la seva saviesa!",
    image: '/images/illustration-25.jpg',
    choices: [],
    ending: "FI - Has curat el bosc!",
  },
  {
    id: 26,
    title: 'FINAL OBERT',
    text: "La Ivet i la Judit decideixen crear una nova Perla de Llum. Ajuden la sirena a reunir llum de lluna, gotes de rosada i un fragment del cor del bosc. \"Creació nova, neix amb força!\" La nova perla és diferent: té colors que canvien i una màgia mai vista abans. Quan la col·loquen al fons del llac, l'aigua es purifica, però la màgia és diferent de l'original. El bosc es transforma en un lloc nou ple de sorpreses. La sirena somriu: \"Heu creat alguna cosa única. Ara haurem d'aprendre com funciona juntes.\"",
    image: '/images/illustration-26.jpg',
    choices: [],
    ending: "FI - Màgia nova per descobrir!",
  },
  {
    id: 27,
    title: 'FINAL BO',
    text: "La Ivet agafa totes les ampolles i les col·loca en cercle. \"Neutralització completa!\" Un remolí de llum blanca desintegra totes les pocions contaminants. L'aigua del llac comença a clarificar-se fins que torna a ser transparent com el cristall. La sirena surt de l'aigua emocionada. \"Heu salvat el meu llac i tot el bosc!\" Com a agraïment, atorga a les tres germanes el títol de Protectores del Bosc i els dóna la capacitat de respirar sota l'aigua sempre que vulguin. Les nenes han triomfat amb saviesa i coratge!",
    image: '/images/illustration-27.jpg',
    choices: [],
    ending: "FI - Heroïnes del llac!",
  },
  {
    id: 28,
    title: 'FINAL DOLENT',
    text: "La Ivet i la Judit decideixen seguir el rastre de les ampolles. El camí les porta a una cabana amagada on viu una bruixa malvada. Quan hi arriben, la bruixa les estava esperant. \"Així que sou vosaltres les entremaliades!\" Amb un encanteri ràpid, les atrapa en gàbies màgiques. Aconsegueixen escapar després d'hores, però la bruixa continua lliure i ara sap qui són. El bosc encara està en perill i han perdut l'efecte sorpresa. Hauran de ser molt més astutes la propera vegada per derrotar-la.",
    image: '/images/illustration-28.jpg',
    choices: [],
    ending: "FI - La lluita continua",
  },
  {
    id: 29,
    title: 'FINAL BO',
    text: "La Ivet no dubta. \"Llibertat immediata!\" La gàbia de llum es trenca i la fada Guardiana queda lliure. Immediatament, les seves ales recuperen la brillantor i creix fins a la seva mida natural. La fada vola pel bosc escampant pols màgica que restaura tota la màgia perduda. Les flors tornen a brillar, les criatures recuperen poders i tot torna a la normalitat. \"Gràcies, valentes germanes! Heu salvat el bosc.\" La fada els dóna un regal: tres plomes màgiques que sempre les protegiran. El bosc celebra amb una festa increïble!",
    image: '/images/illustration-29.jpg',
    choices: [],
    ending: "FI - Missió completa!",
  },
  {
    id: 30,
    title: 'FINAL EXCEL·LENT',
    text: "La Ivet s'asseu al costat de la fada. \"Abans d'alliberar-te, explica'ns què va passar.\" La fada Guardiana relata com una bruixa envejosa la va empresonar per robar-li els poders. \"He estat aquí cent anys esperant algú prou savi per escoltar primer.\" La Ivet allibera la fada, que no només restaura la màgia sinó que també ensenya a les tres germanes els secrets antics de protecció del bosc. Les germanes reben poders especials: l'Ivet control sobre plantes, l'Emma comunicació amb animals, i la Judit visió màgica. Ara són les Guardianes Oficials del Bosc Màgic!",
    image: '/images/illustration-30.jpg',
    choices: [],
    ending: "FI - El millor final possible! Sou llegendàries!",
  },
];
